# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RwVNCUjJ2gspGNglpZXyTQNUU1Mq7bQr
"""

import streamlit as st
import pandas as pd
import joblib
import numpy as np
import os
import json

# --- 1. Load Model yang sudah disimpan ---
@st.cache_resource
def load_models():
    missing_files = []
    required_files = [
        "rf_model.pkl",
        "xgb_model.pkl",
        "label_encoder.pkl",
        "feature_names.pkl",
        "model_info.json"
    ]

    for f in required_files:
        if not os.path.exists(f):
            missing_files.append(f)

    if missing_files:
        st.error(f"File berikut tidak ditemukan: {', '.join(missing_files)}")
        st.error("Harap jalankan 'train_model.py' untuk menghasilkan file model.")
        return None, None, None, 0.0, 0.0

    # Load models
    rf_model = joblib.load("rf_model.pkl")
    xgb_model = joblib.load("xgb_model.pkl")
    le = joblib.load("label_encoder.pkl")
    feature_names = joblib.load("feature_names.pkl")

    # Load accuracy
    with open("model_info.json", "r") as f:
        info = json.load(f)

    return (
        rf_model,
        xgb_model,
        le,
        info.get("rf_accuracy", 0.0),
        info.get("xgb_accuracy", 0.0)
    )

rf_model, xgb_model, le, rf_acc, xgb_acc = load_models()

if rf_model is None:
    st.stop()

# --- 2. UI Header ---
st.set_page_config(page_title="Prediksi Obesitas", layout="wide")
st.title("BMI Classification Predictor (Random Forest & XGBoost)")
st.caption(f"Random Forest Accuracy: **{rf_acc:.4f}** | XGBoost Accuracy: **{xgb_acc:.4f}**")
st.markdown("---")


# --- 3. Form Input User ---
st.sidebar.header("Input Parameter")

def user_input_features():
    gender = st.sidebar.selectbox("Gender", ["Female", "Male"])
    age = st.sidebar.slider("Usia (Tahun)", 10, 100, 25)
    height = st.sidebar.number_input("Tinggi Badan (m)", 1.00, 2.50, 1.70, 0.01)
    weight = st.sidebar.number_input("Berat Badan (kg)", 30.0, 200.0, 70.0, 0.1)

    family_history = st.sidebar.selectbox("Riwayat Obesitas di Keluarga", ["yes", "no"])
    favc = st.sidebar.selectbox("Sering Makan Kalori Tinggi (FAVC)", ["yes", "no"])
    fcvc = st.sidebar.slider("Konsumsi Sayur (FCVC)", 1.0, 3.0, 2.0, 0.1)
    ncp = st.sidebar.slider("Jumlah Makan Utama (NCP)", 1.0, 4.0, 3.0, 0.1)
    caec = st.sidebar.selectbox("Ngemil (CAEC)", ["no", "Sometimes", "Frequently", "Always"])

    smoke = st.sidebar.selectbox("Merokok", ["yes", "no"])
    ch2o = st.sidebar.slider("Konsumsi Air (CH2O)", 1.0, 3.0, 2.0, 0.1)
    scc = st.sidebar.selectbox("Monitor Kalori (SCC)", ["yes", "no"])
    faf = st.sidebar.slider("Aktivitas Fisik (FAF)", 0.0, 3.0, 1.0, 0.1)
    tue = st.sidebar.slider("Waktu Gadget (TUE)", 0.0, 2.0, 1.0, 0.1)

    calc = st.sidebar.selectbox("Konsumsi Alkohol (CALC)", ["no", "Sometimes", "Frequently", "Always"])
    mtrans = st.sidebar.selectbox("Transportasi (MTRANS)", ["Public_Transportation", "Automobile", "Motorbike", "Bike", "Walking"])

    data = {
        'Gender': gender,
        'Age': age,
        'Height': height,
        'Weight': weight,
        'family_history_with_overweight': family_history,
        'FAVC': favc,
        'FCVC': fcvc,
        'NCP': ncp,
        'CAEC': caec,
        'SMOKE': smoke,
        'CH2O': ch2o,
        'SCC': scc,
        'FAF': faf,
        'TUE': tue,
        'CALC': calc,
        'MTRANS': mtrans
    }
    return pd.DataFrame(data, index=[0])

input_df = user_input_features()


# --- 4. Layout Hasil ---
col1, col2 = st.columns([1, 2])

with col1:
    st.subheader("Data Input Anda")
    st.dataframe(input_df.T)

    st.markdown("---")

    model_choice = st.radio("Pilih Model:", ["Random Forest", "XGBoost"], index=0)

    if st.button("PREDIKSI", type="primary"):
        model = rf_model if model_choice == "Random Forest" else xgb_model

        prediction = model.predict(input_df)
        prediction_proba = model.predict_proba(input_df)

        predicted_label = le.inverse_transform(prediction)[0]

        with col2:
            st.subheader(f"Hasil Prediksi ({model_choice})")

            if "Obesity" in predicted_label:
                st.error(f"⚠️ **{predicted_label}**")
            elif "Overweight" in predicted_label:
                st.warning(f"⚠️ **{predicted_label}**")
            else:
                st.success(f"✅ **{predicted_label}**")

            st.markdown("---")
            st.write("Probabilitas:")
            proba_df = pd.DataFrame(
                prediction_proba.T,
                index=le.classes_,
                columns=["Probabilitas"]
            )
            st.bar_chart(proba_df)

    else:
        with col2:
            st.info("Isi parameter di sidebar lalu klik PREDIKSI.")