# -*- coding: utf-8 -*-
"""Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AYQrscxw_iPzNsfkJ5zxwHXmQBHBPkLL
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
import joblib
from sklearn.metrics import accuracy_score
import json

# --- 1. Load Dataset ---
try:
    df = pd.read_csv("obesity_level.csv")
    print("Data berhasil dimuat.")
except FileNotFoundError:
    print("ERROR: File 'obesity_level.csv' tidak ditemukan. Pastikan file ada di direktori yang sama.")
    exit()

# Rename kolom target jika belum sesuai
if '0be1dad' in df.columns:
    df.rename(columns={'0be1dad': 'Obesity Level'}, inplace=True)

# Pisahkan Fitur dan Target
X = df.drop(columns=['id', 'Obesity Level'], errors='ignore')
y = df['Obesity Level']

# --- 2. Preprocessing Pipeline ---
cat_cols = X.select_dtypes(include=['object']).columns.tolist()
num_cols = X.select_dtypes(include=['float64', 'int64']).columns.tolist()

num_transformer = StandardScaler()
cat_transformer = OneHotEncoder(handle_unknown='ignore')

preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_transformer, num_cols),
        ('cat', cat_transformer, cat_cols)
    ]
)

# Encode Target
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)
print(f"Data split: {len(X_train)} training samples, {len(X_test)} testing samples.")

# --- 3. Model Random Forest ---
rf_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=150, max_depth=15, random_state=42))
])

print("\n[+] Sedang melatih Random Forest (RF)...")
rf_pipeline.fit(X_train, y_train)

y_pred_rf = rf_pipeline.predict(X_test)
rf_acc = accuracy_score(y_test, y_pred_rf)
print(f"Random Forest Test Accuracy: {rf_acc:.4f}")

# --- 4. Model XGBoost ---
xgb_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', XGBClassifier(
        n_estimators=150,
        learning_rate=0.1,
        eval_metric='mlogloss',
        random_state=42
    ))
])

print("\n[+] Sedang melatih XGBoost...")
xgb_pipeline.fit(X_train, y_train)

y_pred_xgb = xgb_pipeline.predict(X_test)
xgb_acc = accuracy_score(y_test, y_pred_xgb)
print(f"XGBoost Test Accuracy: {xgb_acc:.4f}")

# --- 5. Simpan Model dan Encoder Secara Terpisah ---

# 1. Random Forest model
joblib.dump(rf_pipeline, 'rf_model.pkl')
print("[SUCCESS] Random Forest model disimpan sebagai 'rf_model.pkl'")

# 2. XGBoost model
joblib.dump(xgb_pipeline, 'xgb_model.pkl')
print("[SUCCESS] XGBoost model disimpan sebagai 'xgb_model.pkl'")

# 3. Label Encoder
joblib.dump(le, 'label_encoder.pkl')
print("[SUCCESS] Label Encoder disimpan sebagai 'label_encoder.pkl'")

# 4. Nama Fitur
joblib.dump(X.columns.tolist(), 'feature_names.pkl')
print("[SUCCESS] Feature names disimpan sebagai 'feature_names.pkl'")

# 5. Info akurasi
model_info = {
    'rf_accuracy': float(rf_acc),
    'xgb_accuracy': float(xgb_acc)
}

with open('model_info.json', 'w') as f:
    json.dump(model_info, f, indent=4)

print("[SUCCESS] Info akurasi disimpan sebagai 'model_info.json'")